# Generated by Django 5.0.1 on 2024-01-28 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect', models.CharField(max_length=20)),
                ('sentiment', models.CharField(choices=[('NEG', 'NEG'), ('POS', 'POS'), ('NEU', 'NEU')], max_length=3)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.statement')),
            ],
        ),
    ]
